### ISSUE TITLE
Logout does not work because it invalidates the refresh token and not the access token

### ISSUE THREAD

**Issue by williamdes** [anson-vandoren/mailfeed#3]
Logout + JWT feels weird. I already do this at work, but in your implementation it does not work.
It would be best to switch to api tokens rather than JWTs if logout is needed.
A JWT expires but can not be logged out, you can only apply software hacks (like I do at work) to make it invalid in a middleware

**Comment by anson-vandoren** [comment]
Yeah, JWT was def the wrong choice here. Not sure when I'll get back around to doing any non-trivial work on this repo, but a simple API token is probably the right way to go

**Comment by williamdes** [comment]
Let's close this as for now it just works fine
A token in the ENV would maybe be sufficient to admin the API ?
